apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: test-pod-kill
  namespace: test
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - test
    labelSelectors:
      app: nginx-target
