# CHAOS_AGENT_ROLE_ARN / FIS_TEMPLATE_* / TABLE_NAME は
# terraform apply 後に CI/CD で kubectl set env により設定する
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chaos-agent
  namespace: chaos
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::203553641035:role/chaos-agent-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaos-agent
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: chaos-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chaos-agent
subjects:
  - kind: ServiceAccount
    name: chaos-agent
    namespace: chaos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chaos-agent
  namespace: chaos
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: chaos-agent
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaos-agent
    spec:
      serviceAccountName: chaos-agent
      automountServiceAccountToken: true
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: chaos-agent
          image: 203553641035.dkr.ecr.ap-northeast-1.amazonaws.com/chaos-platform/chaos-agent:latest
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          env:
            - name: TABLE_NAME
              value: chaos-platform-experiment-history
            - name: AWS_REGION
              value: ap-northeast-1
            - name: SERVICE_B_URL
              value: http://k8s-default-serviceb-64e7c32426-1389829488.ap-northeast-1.elb.amazonaws.com/items/1
            - name: TRAFFIC_GEN_INTERVAL
              value: "30"
            - name: ALB_ORIGIN_SECRET
              value: fLORutDU9AqgI2QQl5tbQspmOYRZdSIi
            - name: SERVICE_A_AGGREGATE_URL
              value: "http://service-a.default/aggregate/1"
          resources:
            requests:
              cpu: "64m"
              memory: "128Mi"
            limits:
              cpu: "256m"
              memory: "256Mi"
