grafana:
  enabled: true
  adminPassword: ""  # Secrets Manager から手動設定 or helm --set で注入
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: "${grafana_irsa_role_arn}"  # terraform output grafana_irsa_role_arn
  service:
    type: ClusterIP  # ALB Ingress Controller 経由でアクセス
  persistence:
    enabled: true
    size: 10Gi
  additionalDataSources:
  - name: CloudWatch
    type: cloudwatch
    jsonData:
      authType: default
      defaultRegion: ap-northeast-1
  - name: X-Ray
    type: grafana-x-ray-datasource
    jsonData:
      authType: default
      defaultRegion: ap-northeast-1

prometheus:
  prometheusSpec:
    retention: 15d
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi

nodeExporter:
  enabled: true

alertmanager:
  enabled: true
